AY2223S2-CS2103-W17-2/tp

docs/team/axmszr.md

Update axmszr.md PPP (oops)

---

docs/team/valerietanhx.md

Update project portfolio page

---

src/main/java/seedu/address/ui/HelpWindow.java

Update URL in help window to the user guide for Dengue Hotspot Tracker

Update URL in help window

---

README.md

Token v1.1 pull request

---

docs/UserGuide.md
src/main/java/seedu/dengue/ui/HelpWindow.java

- Update Userguide
- Edit userguide
- Edit HelpWindow.java to include more information

Update User guide to include work in progress features and edit Help window to include more information other than the website to the User guide

---

.github/workflows/gradle.yml
src/main/java/seedu/dengue/model/util/SampleDataUtil.java
src/main/java/seedu/dengue/ui/HelpWindow.java

- Additionally update seedu.dengue/model/util/SampleDataUtil.java

Update CI Pass Condition

---

src/main/java/seedu/dengue/commons/core/Messages.java
src/main/java/seedu/dengue/model/person/Age.java
src/main/java/seedu/dengue/model/person/Postal.java
src/main/java/seedu/dengue/ui/HelpWindow.java

The messages displayed to users when invalid input is entered are not clear enough.
Making them clearer will allow the user to correct their mistakes in the invalid input more easily.
Let's update our messages to be more informative and precise.
Closes #65

Update error messages

---

src/main/java/seedu/dengue/ui/PersonCard.java
src/main/java/seedu/dengue/ui/UiManager.java
src/main/resources/view/DengueTheme.css
src/main/resources/view/Extensions.css
src/main/resources/view/HelpWindow.css
src/main/resources/view/HelpWindow.fxml
src/main/resources/view/MainWindow.fxml
src/main/resources/view/PersonListCard.fxml

The original AB3 GUI does not provide a visually appealing experience.
Brightening the color palette and rearranging the elements in each PersonCard will help with both readability and enjoyment.
Let's choose a green-grey/brown color palette to begin our journey with, and spread out the details of a Case about the space provided.
Closes #15, closes #21

Update GUI color palette

---

src/main/java/seedu/dengue/model/person/Person.java
src/test/java/seedu/dengue/model/DengueHotspotTrackerTest.java
src/test/java/seedu/dengue/model/person/PersonTest.java
src/test/java/seedu/dengue/model/person/UniquePersonListTest.java

Now, only those with the same name, postal code and age will be considered the same person.

resolve issue #107 and add/edit tests for unique persons

---

src/main/java/seedu/dengue/logic/commands/DeleteCommand.java
src/main/java/seedu/dengue/logic/parser/DeleteCommandParser.java
src/main/java/seedu/dengue/logic/parser/Parser.java
src/main/java/seedu/dengue/logic/parser/ParserUtil.java
src/main/java/seedu/dengue/model/person/SubPostal.java
src/test/java/seedu/dengue/logic/commands/DeleteCommandTest.java

Add multi-index delete functionality

---

src/main/java/seedu/dengue/logic/analyst/AgeAnalyst.java
src/main/java/seedu/dengue/logic/analyst/PostalAnalyst.java
src/main/java/seedu/dengue/logic/analyst/VariantAnalyst.java
src/main/java/seedu/dengue/model/overview/AgeOverview.java
src/main/java/seedu/dengue/model/overview/Overview.java

Clean up comments, remove magic numbers, make EnumMap more explicit.

Clean up Analyst and Overview

---

src/main/java/seedu/dengue/model/person/PostalLocationMapping.java

For some reason Sam has authorship of the entire file, which isn't the case :")

Shift authorship of PostalLocationMapping

---

src/main/java/seedu/dengue/commons/util/StringUtil.java
src/main/java/seedu/dengue/logic/commands/FindCommand.java
src/main/java/seedu/dengue/logic/parser/DeleteCommandParser.java
src/main/java/seedu/dengue/logic/parser/FindCommandParser.java
src/main/java/seedu/dengue/model/predicate/FindPredicate.java
src/main/java/seedu/dengue/model/predicate/PersonContainsNamePredicate.java
src/main/java/seedu/dengue/model/predicate/PersonContainsPostalPredicate.java
src/main/java/seedu/dengue/model/predicate/RangeContainsPersonPredicate.java
src/main/java/seedu/dengue/model/range/EndAge.java
src/main/java/seedu/dengue/model/range/EndDate.java
src/main/java/seedu/dengue/model/range/StartAge.java
src/main/java/seedu/dengue/model/range/StartDate.java
src/test/java/seedu/dengue/logic/commands/ClearCommandTest.java
src/test/java/seedu/dengue/logic/commands/CommandTestUtil.java
src/test/java/seedu/dengue/logic/commands/FindCommandTest.java

Fix find so that it can take multiple words in names by making a new function in stringutil which checks for substrings that are multiple words long. 
Add functionality to find so that it can accept both date ranges as well as age ranges

Fix find so that it can take multiple words in names and find for date ranges and age ranges

---

src/main/java/seedu/dengue/commons/util/CsvUtil.java
src/test/data/CsvDengueHotspotTrackerStorageTest/duplicatePersonDengueHotspotTracker.csv
src/test/data/CsvDengueHotspotTrackerStorageTest/invalidAndValidPersonDengueHotspotTracker.csv
src/test/data/CsvDengueHotspotTrackerStorageTest/invalidPersonDengueHotspotTracker.csv
src/test/data/CsvDengueHotspotTrackerStorageTest/typicalPersonsDengueHotspotTracker.csv

Update CSV format to have quotation marks

Update csv format to have quotation marks

---

src/main/java/seedu/dengue/model/predicate/FindPredicate.java
src/main/java/seedu/dengue/model/predicate/PersonContainsAgePredicate.java
src/main/java/seedu/dengue/model/predicate/PersonContainsDatePredicate.java
src/main/java/seedu/dengue/model/predicate/PersonContainsNamePredicate.java
src/main/java/seedu/dengue/model/predicate/PersonContainsPostalPredicate.java
src/main/java/seedu/dengue/model/predicate/PersonContainsVariantsPredicate.java
src/main/java/seedu/dengue/model/predicate/PredicateUtil.java
src/main/java/seedu/dengue/model/predicate/RangeContainsPersonPredicate.java

Abstract out compose "and" functions

Predicate tidy

---

src/main/java/seedu/dengue/logic/commands/SortCommand.java
src/main/java/seedu/dengue/logic/parser/OverviewCommandParser.java
src/main/java/seedu/dengue/logic/parser/SortCommandParser.java
src/test/java/seedu/dengue/logic/commands/SortCommandTest.java
src/test/java/seedu/dengue/logic/parser/SortCommandParserTest.java

Test cases for SortCommand and SortCommandParser
*No need to delete this branch, will continue to use this to add more test cases in v1.4!

Test cases for sort feature

---

docs/UserGuide.md
src/main/java/seedu/dengue/logic/commands/SortCommand.java
src/main/java/seedu/dengue/logic/comparators/PersonPostalComparator.java
src/main/java/seedu/dengue/logic/comparators/PostalComparator.java
src/main/java/seedu/dengue/logic/parser/SortCommandParser.java
src/main/java/seedu/dengue/model/person/Postal.java
src/test/java/seedu/dengue/logic/commands/SortCommandTest.java
src/test/java/seedu/dengue/logic/parser/SortCommandParserTest.java

*Sorry branch name is misleading!! Forgot to git checkout :")
Have updated UG as well

Add sort by postal functionality

---

src/main/java/seedu/dengue/model/DengueHotspotTracker.java
src/main/java/seedu/dengue/model/ReadOnlyDengueHotspotTracker.java
src/main/java/seedu/dengue/model/person/Date.java
src/main/java/seedu/dengue/model/person/Name.java
src/main/java/seedu/dengue/model/person/Person.java
src/main/java/seedu/dengue/storage/temporary/StackWithStorage.java
src/test/java/seedu/dengue/model/person/NameTest.java
src/test/java/seedu/dengue/model/person/PersonTest.java
src/test/java/seedu/dengue/testutil/PersonBuilder.java

- names with additional whitespaces e.g. "harold                                                               wilson" will become "harold wilson"
- names will not allow alphanumeric characters e.g. "harold wi1s0n" will be rejected.
Closes #75

Edit names

---

src/main/java/seedu/dengue/logic/Logic.java
src/main/java/seedu/dengue/logic/LogicManager.java
src/main/java/seedu/dengue/logic/analyst/PostalAnalyst.java
src/main/java/seedu/dengue/model/overview/Overview.java
src/main/java/seedu/dengue/ui/DataBinCard.java
src/main/java/seedu/dengue/ui/MainWindow.java
src/main/java/seedu/dengue/ui/OverviewDisplay.java
src/main/resources/view/DataBinListCard.fxml
src/main/resources/view/OverviewDisplay.fxml

- Update gui view and logic
- Update gui view and logic make it pretty

new overview gui logic

---

src/main/java/seedu/dengue/logic/parser/DeleteCommandParser.java
src/main/java/seedu/dengue/logic/parser/FindCommandParser.java
src/main/java/seedu/dengue/model/person/Age.java
src/main/java/seedu/dengue/model/person/ContinuousData.java
src/main/java/seedu/dengue/model/person/Date.java
src/main/java/seedu/dengue/model/predicate/RangeContainsPersonPredicate.java
src/main/java/seedu/dengue/model/range/Range.java
src/test/java/seedu/dengue/logic/commands/ClearCommandTest.java
src/test/java/seedu/dengue/logic/commands/CommandTestUtil.java
src/test/java/seedu/dengue/logic/commands/FindCommandTest.java
src/test/java/seedu/dengue/logic/commands/SortCommandTest.java

Create interface for continuous data
Use <? extends Continuous data>.

Resolve unsafe use of Range without generics

---

docs/UserGuide.md

Pipe and nbsp characters were not displaying properly. Fixed for markdown

Fix UG symbols

---

docs/UserGuide.md
src/main/java/seedu/dengue/model/person/Name.java

Resolves #227, #189, #193 and #186

Fix all documentation and formatting issues with names 

---

src/main/java/seedu/dengue/commons/core/index/Index.java
src/main/java/seedu/dengue/logic/commands/DeleteCommand.java

Fix success message when duplicate indexes given for delete

---

docs/UserGuide.md
src/main/java/seedu/dengue/logic/commands/DeleteCommand.java
src/main/java/seedu/dengue/logic/commands/EditCommand.java
src/main/java/seedu/dengue/logic/commands/ListCommand.java
src/main/java/seedu/dengue/model/person/Name.java

Also made tiny fix to list command success message to better match UG
Closes #178, #192

Fix UG and invalid command messages for too-large indexes

---

src/test/java/seedu/dengue/logic/commands/DeleteCommandTest.java
src/test/java/seedu/dengue/logic/parser/DeleteCommandParserTest.java

Added for both DeleteCommandTest and DeleteCommandParserTest

Add test cases for multi-index delete

---

src/main/java/seedu/dengue/model/person/Location.java

Update Location enum with missed sector.

Add 91 to DIST17

---

src/main/resources/view/DengueTheme.css

Occurs when the URL is clicked

Fix bug which changes Help message's font

---

docs/UserGuide.md

Fix UG formatting nits

---

docs/UserGuide.md
src/main/java/seedu/dengue/commons/core/GuiSettings.java
src/main/java/seedu/dengue/commons/core/Messages.java
src/main/java/seedu/dengue/logic/parser/ParserUtil.java

And some other small bug fixes

Fix MESSAGE_UNKNOWN_COMMAND

---

docs/team/axmszr.md
docs/team/markusyeo.md
docs/team/sumhungyee.md
docs/team/tohtoroo.md
docs/team/valerietanhx.md

PPP template

---

src/main/java/seedu/dengue/commons/util/CsvUtil.java
src/main/java/seedu/dengue/logic/commands/ImportCommand.java
src/main/java/seedu/dengue/model/ModelManager.java
src/main/java/seedu/dengue/model/overview/Overview.java
src/main/java/seedu/dengue/model/person/Person.java
src/main/java/seedu/dengue/model/person/UniquePersonList.java
src/main/java/seedu/dengue/model/person/exceptions/PersonHasNullAttributesException.java
src/main/java/seedu/dengue/storage/CsvDengueHotspotStorage.java

- Add null attribute checker to Person
- Throw appropriate command in ImportCommand
- Fix display of variants

Catch Error when fed in wrong CSV files

---

src/main/java/seedu/dengue/logic/analyst/Analyst.java
src/main/java/seedu/dengue/logic/analyst/DataBin.java
src/main/java/seedu/dengue/model/person/Person.java
src/test/java/seedu/dengue/logic/analyst/AgeAnalystTest.java
src/test/java/seedu/dengue/logic/analyst/DataBinTest.java
src/test/java/seedu/dengue/logic/analyst/PostalAnalystTest.java
src/test/java/seedu/dengue/logic/analyst/VariantAnalystTest.java

and for DataBin too.
Overview test cases coming soon.
Closes #117

Add Analyst test cases

---

src/test/java/seedu/dengue/logic/analyst/AgeAnalystTest.java
src/test/java/seedu/dengue/logic/analyst/PostalAnalystTest.java
src/test/java/seedu/dengue/logic/analyst/VariantAnalystTest.java
src/test/java/seedu/dengue/testutil/PersonBuilder.java
src/test/java/seedu/dengue/testutil/PersonListBuilder.java

Abstracted out the list builder, also for use in the Overview tests.

Improve Analyst tests

---

docs/DeveloperGuide.md

- Update DG
- Make happy markdown

update dg 1
